version: '3.4'

services:
  stackoverflowtags:
    image: ${DOCKER_REGISTRY-}stackoverflowtags
    build:
      context: .
      dockerfile: StackOverflowTags/Dockerfile
    ports:
        - "8000:8000" 
        - "8001:8001"
       